config/routes.rb
Rails.application.routes.draw do
  root 'homes#index'

  resources :cohorts, only: [:index, :show]
  resources :students, only: [:index]
  resources :group_projects, only: [:index, :show] do
    resources :tasks, only: [:show]
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cohort.rb
class Cohort < ApplicationRecord
  has_many :students
  has_many :mentorships
  has_many :mentors, through: :mentorships
  has_many :group_projects

  validates :name, presence: true
  validates :launch_site, presence: true
  validates :city, presence: true
  validates :state, presence: true, length: { is: 2 }

end

app/models/group_project.rb
class GroupProject < ApplicationRecord
  belongs_to :cohort
  has_many :students
  has_many :tasks

  validates :group_name, presence: true
  validates :project_name, presence: true
end

app/models/mentor.rb
class Mentor < ApplicationRecord
  has_many :students
  has_many :mentorships
  has_many :cohorts, through: :mentorships

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :nickname, numericality: false
  validates :motivation, presence: true
  validates :specialty, presence: true

end

app/models/mentorship.rb
class Mentorship < ApplicationRecord
  belongs_to :mentor
  belongs_to :cohort

  validates :mentor_id, presence: true, numericality: true
  validates :cohort_id, presence: true, numericality: true
end

app/models/student.rb
class Student < ApplicationRecord
  belongs_to :mentor
  belongs_to :cohort
  belongs_to :group_project
  has_many :tasks

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :nickname, numericality: false
  validates :motivation, presence: true
  validates :backstory, presence: true

end

app/models/support/database_cleaner.rb
require "database_cleaner"

RSpec.configure do |config|
  config.before(:suite) do
    DatabaseCleaner.clean_with(:truncation)
  end

  config.before(:each) do
    DatabaseCleaner.strategy = :transaction
  end

  config.before(:each) do
    DatabaseCleaner.start
  end

  config.after(:each) do
    DatabaseCleaner.clean
  end
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :student
  belongs_to :group_project

  validates :name, presence: true
  validates :description, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/cohorts_controller.rb
class CohortsController < ApplicationController
  # GET /questions
  def index
    @cohorts = Cohort.all
  end

  def show
    @cohort = Cohort.find(params[:id])
    @students = @cohort.students
    @mentors = @cohort.mentors
  end
end

app/controllers/group_projects_controller.rb
class GroupProjectsController < ApplicationController
  # GET /questions
  def index
    @group_projects = GroupProject.all
  end

  def show
    @group_project = GroupProject.find(params[:id])
  end

end

app/controllers/homes_controller.rb
require 'pry'

class HomesController < ApplicationController
  # GET /questions
  def index
    @cohort = Cohort.last

  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  # GET /questions
  def index
    @students = Student.all
  end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  # GET /questions
  def show
    @project = GroupProject.find(params[:group_project_id])
    @task = Task.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/cohorts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Cohort List:</h1>

<table>
  <tbody>
    <tr>
      <% @cohorts.each do |cohort| %>
      <td><%= link_to "#{cohort.name}", cohort %></td>
      <% end %>
    </tr>
  </tbody>
</table>

<br>

app/views/cohorts/show.html.erb
<p id="notice"><%= notice %></p>

<h1>Cohort Details</h1>

<table>
  <tbody>
    <tr>
      <td><%= link_to "#{@cohort.name}", @cohort %></td>
    </tr>
  </tbody>
</table>

<% @students.each do |student| %>
<%= "#{student.first_name} #{student.last_name}" %>
<br/>
<% end %>

<% @mentors.each do |mentor| %>
<%= "#{mentor.first_name} #{mentor.last_name}" %>
<br/>
<% end %>

<% @cohort.group_projects.each do |project| %>
<%= link_to project.group_name, project %>
<br/>
<% end %>

app/views/group_projects/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Project List:</h1>

<table>
  <tbody>
    <tr>
      <% @group_projects.each do |project| %>
      <td><%= link_to "#{project.group_name}", project %></td>
      <% end %>
    </tr>
  </tbody>
</table>


<%= link_to "Home", root_path%>

app/views/group_projects/show.html.erb
<p id="notice"><%= notice %></p>

<h1><%= @group_project.group_name %> Details</h1>

<table>
  <tbody>
    <tr>
      <h1><%= @group_project.group_name %></h1>
    </tr>
  </tbody>
</table>

<% @group_project.students.each do |student| %>
<%= "#{student.first_name} #{student.last_name}" %>
<br/>
<% end %>

<% @group_project.tasks.each do |task| %>
<%= link_to task.name, group_project_task_path(task) %>
<br/>
<% end %>

<br>

app/views/homes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Welcome to Launch Academy!</h1>

<table>
  <tbody>
    <tr>
      <td><%= link_to @cohort.name, @cohort %></td>
    </tr>
  </tbody>
</table>

<br>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LaMoon</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/students/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Student Roster:</h1>

<table>
  <tbody>
    <tr>
      <% @students.each do |student| %>
      <td><%= "#{student.first_name} #{student.last_name}" %></td>
      <% end %>
    </tr>
  </tbody>
</table>

<%= link_to "Home", root_path%>

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<%= "#{@task.name} Details" %>

<table>
  <tbody>
    <tr>
      <h1><%= @task.name %></h1>
    </tr>
  </tbody>
</table>



<%= "#{@task.description}" %>

<%= "#{@task.student.first_name} #{@task.student.last_name}" %>
<br/>

<br>